get_host_os(HOST_OS)
set(CHOCO_ARCH_X86 "x86")
set(CHOCO_ARCH_X86_64 "AMD64")
set(CHOCO_ARCH_ARM64 "ARM64")
set(CHOCO_ARCH_ALL "all")


set(CHOCO_PACKAGE_EXT .choco)
set(CHOCO_PACKAGE_NAME choco)

set(CHOCOARCH_LIST_WINDOWS "${CHOCO_ARCH_X86_64};${CHOCO_ARCH_ARM64}")
set(ALL_CHOCOARCH_LIST_WINDOWS ${CHOCOARCH_LIST_WINDOWS})
list(APPEND ALL_CHOCOARCH_LIST_WINDOWS ${CHOCO_ARCH_ALL})


message(STATUS "RELEASE_DATE: ${RELEASE_DATE}")

execute_process(
    COMMAND bash -c "date -d '${RELEASE_DATE}' '+%a, %d %b %Y 00:00:00 +0000'"
    OUTPUT_VARIABLE RELEASE_DATE_CHOCO
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

message(STATUS "RELEASE_DATE_CHOCO: ${RELEASE_DATE_CHOCO}")

set(PACKAGE_ROOT_DIR "${CMAKE_BINARY_DIR}/${HOST_OS}/pkg/${CHOCO_PACKAGE_NAME}/${APP_ARCH}/${APP_NAME}")
set(CHOCO_ROOT_DIR "${CMAKE_BINARY_DIR}/choco")
set(CHOCO_BUILD_ROOT_DIR "${CHOCO_ROOT_DIR}")
set(CHOCO_BUILD_CONFIG_DIR "${CHOCO_ROOT_DIR}/")
set(CHOCO_BUILD_PAYLOAD_DIR "${CHOCO_ROOT_DIR}/tools")
set(CHOCO_BUILD_OUTPUT_DIR "${CHOCO_ROOT_DIR}/output")
set(CHOCO_BUILD_TEMP_DIR "${CHOCO_ROOT_DIR}/temp")


