get_host_os(HOST_OS)
set(RPM_ARCH_X86 "i386")
set(RPM_ARCH_X86_64 "x86_64")
set(RPM_ARCH_ARM "armhfp")
set(RPM_ARCH_ARM64 "aarch64")
set(RPM_ARCH_ALL "all")


set(RPM_PACKAGE_EXT .rpm)
set(RPM_PACKAGE_NAME rpm)
set(RPM_PACK_TYPE "source")
set(RPM_BASE "core22")

set(RPMARCH_LIST_LINUX "${RPM_ARCH_X86};${RPM_ARCH_X86_64};${RPM_ARCH_ARM};${RPM_ARCH_ARM64}")
set(ALL_RPMARCH_LIST_LINUX ${RPMARCH_LIST_LINUX})
list(APPEND ALL_RPMARCH_LIST_LINUX ${RPM_ARCH_ALL})


message(STATUS "RELEASE_DATE: ${RELEASE_DATE}")

execute_process(
    COMMAND bash -c "date -d '${RELEASE_DATE}' '+%a, %d %b %Y 00:00:00 +0000'"
    OUTPUT_VARIABLE RELEASE_DATE_RPM
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

message(STATUS "RELEASE_DATE_RPM: ${RELEASE_DATE_RPM}")

set(PACKAGE_ROOT_DIR "${CMAKE_BINARY_DIR}/${HOST_OS}/pkg/${RPM_PACKAGE_NAME}/${APP_ARCH}/${APP_NAME}")
set(RPM_ROOT_DIR "${CMAKE_BINARY_DIR}/rpm")
set(RPM_BUILD_ROOT_DIR "${RPM_ROOT_DIR}")
set(RPM_BUILD_BUILD_DIR "${RPM_ROOT_DIR}/rpmbuild")
set(RPM_BUILD_CONFIG_DIR "${RPM_ROOT_DIR}/${APP_NAME}")
set(RPM_BUILD_PAYLOAD_DIR "${RPM_BUILD_CONFIG_DIR}/SOURCES")
set(RPM_BUILD_OUTPUT_DIR "${RPM_ROOT_DIR}/output")
set(RPM_BUILD_TEMP_DIR "${RPM_ROOT_DIR}/temp")


