type: Resource
kind: Data
name: Product_SeedData
metadata:
specifications:
  name: Product
  set: EShopping
  data:
    - id: 10b84b2b-7cc0-56c8-8cd2-708aa443d7a1
      name: Nike Shoes
      price: 3375
      imageFile: images/products/nike-shoes.jpg
      summary: "Nike Shoes summ.."
      types:
        id: 0e56e7b1-1635-5733-a6c0-9b9328db5e3a
        name: Shoes
      brands:
        id: 9ae4671e-8d35-522e-8315-dd562f19f102
        name: Nike
      description: |
        Nike, Inc. is an American multinational corporation that designs, develops, manufactures, and markets footwear, apparel, equipment, accessories, and services.

    - id: 912d8b4b-8292-5d59-be48-ca198607637f
      name: iPhone 15
      price: 3375
      imageFile: images/products/nike-shoes.jpg
      summary: "IPhone summ.."
      types:
        id: 84309aec-6025-5ab7-9e40-d19eb6d4c217
        name: Smart Phone
      brands:
        id: 00470e36-9c22-58e5-8436-93391a6f4baa
        name: Apple
      description: |
        Apple Decription