sonar.host.url=http://localhost:9000
sonar.projectName=pars
sonar.projectKey=pars
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=tests
sonar.exclusions=vendor/**, dist/**
sonar.test.inclusions=**/*_test.go
sonar.typescript.lcov.reportPaths=coverage/lcov.info