file(WRITE ${CONFIG_FILE_PATH} "class ${PROJECT_NAME} < Formula\n")
file(APPEND ${CONFIG_FILE_PATH} "\tdesc \"${PROJECT_SUMMARY}\"\n")
file(APPEND ${CONFIG_FILE_PATH} "\thomepage \"${PROJECT_HOMEPAGE}\"\n")
file(APPEND ${CONFIG_FILE_PATH} "\turl \"${PROJECT_HOMEPAGE}\"\n")
file(APPEND ${CONFIG_FILE_PATH} "\tsha256 \"${PROJECT_HOMEPAGE}\"\n")
file(APPEND ${CONFIG_FILE_PATH} "\tlicense \"${PROJECT_LICENCE_TYPE}\"\n")
file(APPEND ${CONFIG_FILE_PATH} "\n\n")
file(APPEND ${CONFIG_FILE_PATH} "\tdef install\n")
file(APPEND ${CONFIG_FILE_PATH} "\t\tbin.install \"${APP_NAME}\"\n")
file(APPEND ${CONFIG_FILE_PATH} "\tend\n")
file(APPEND ${CONFIG_FILE_PATH} "\n\n")
file(APPEND ${CONFIG_FILE_PATH} "\ttest do\n")
file(APPEND ${CONFIG_FILE_PATH} "\t\tsystem \"#bin/${APP_NAME}\", \"info\"\n")
file(APPEND ${CONFIG_FILE_PATH} "\tend\n")
file(APPEND ${CONFIG_FILE_PATH} "end\n")
