set(IS_WINDOWS FALSE)
set(IS_UNIX_BASED FALSE)
set(IS_DARWIN FALSE)
set(IS_LINUX FALSE)
set(IS_DEBIAN FALSE)
set(IS_REDHAT FALSE)
set(IS_ARCH_LINUX FALSE)
set(IS_SUSE FALSE)
set(IS_BSD FALSE)
set(IS_FREEBSD FALSE)
set(IS_OPENBSD FALSE)
set(IS_NETBSD FALSE)

if(WIN32)
    set(IS_WINDOWS TRUE)
elseif(APPLE)
    set(IS_DARWIN TRUE)
    set(IS_UNIX_BASED TRUE)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(IS_LINUX TRUE)
    set(IS_UNIX_BASED TRUE)

    if(EXISTS "/etc/debian_version")
        set(IS_DEBIAN TRUE)
    elseif(EXISTS "/etc/redhat-release")
        set(IS_REDHAT TRUE)
    elseif(EXISTS "/etc/arch-release")
        set(IS_ARCH_LINUX TRUE)
    elseif(EXISTS "/etc/SuSE-release")
        set(IS_SUSE TRUE)
    endif()
elseif(CMAKE_SYSTEM_NAME STREQUAL "FreeBSD")
    set(IS_FREEBSD TRUE)
    set(IS_UNIX_BASED TRUE)
elseif(CMAKE_SYSTEM_NAME STREQUAL "OpenBSD")
    set(IS_OPENBSD TRUE)
    set(IS_UNIX_BASED TRUE)
elseif(CMAKE_SYSTEM_NAME STREQUAL "NetBSD")
    set(IS_NETBSD TRUE)
    set(IS_UNIX_BASED TRUE)
endif()

function(get_host_os host_os)    
    if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
        set(${host_os} ${OS_LINUX} PARENT_SCOPE)
    elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Darwin")
        set(${host_os} ${OS_MACOS} PARENT_SCOPE)
    elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
        set(${host_os} ${OS_WINDOWS} PARENT_SCOPE)
    else()
        message(FATAL_ERROR "Unsupported host OS: ${CMAKE_HOST_SYSTEM_NAME}")
    endif()
endfunction()


function(get_host_arch host_arch)
    if(CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "x86_64" OR CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "AMD64")
        set(${host_arch} ${ARCH_X86_64} PARENT_SCOPE)
    elseif(CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "i[3-6]86")
        set(${host_arch} ${ARCH_X86} PARENT_SCOPE)
    elseif(CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "aarch64")
        set(${host_arch} ${ARCH_ARM64} PARENT_SCOPE)
    elseif(CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "armv7l" OR CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "arm")
        set(${host_arch} ${ARCH_ARM} PARENT_SCOPE)
    else()
        message(FATAL_ERROR "Unsupported architecture: ${CMAKE_HOST_SYSTEM_PROCESSOR}")
    endif()
endfunction()