set(IS_WINDOWS FALSE)
set(IS_DARWIN FALSE)
set(IS_LINUX FALSE)
set(IS_DEBIAN FALSE)
set(IS_REDHAT FALSE)
set(IS_BSD FALSE)
set(IS_ARCH_LINUX FALSE)
set(IS_SUSE FALSE)
set(IS_FREEBSD FALSE)
set(IS_OPENBSD FALSE)
set(IS_NETBSD FALSE)

if(WIN32)
    set(IS_WINDOWS TRUE)
elseif(APPLE)
    set(IS_DARWIN TRUE)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(IS_LINUX TRUE)

    if(EXISTS "/etc/debian_version")
        set(IS_DEBIAN TRUE)
    elseif(EXISTS "/etc/redhat-release")
        set(IS_REDHAT TRUE)
    elseif(EXISTS "/etc/arch-release")
        set(IS_ARCH_LINUX TRUE)
    elseif(EXISTS "/etc/SuSE-release")
        set(IS_SUSE TRUE)
    endif()
elseif(CMAKE_SYSTEM_NAME STREQUAL "FreeBSD")
    set(IS_FREEBSD TRUE)
elseif(CMAKE_SYSTEM_NAME STREQUAL "OpenBSD")
    set(IS_OPENBSD TRUE)
elseif(CMAKE_SYSTEM_NAME STREQUAL "NetBSD")
    set(IS_NETBSD TRUE)
endif()
