get_host_os(HOST_OS)
set(SNAP_ARCH_X86 "i386")
set(SNAP_ARCH_X86_64 "amd64")
set(SNAP_ARCH_ARM "armhf")
set(SNAP_ARCH_ARM64 "arm64")
set(SNAP_ARCH_ALL "all")


set(SNAP_SERIES jammy) #focal
set(SNAP_PACKAGE_EXT .snap)
set(SNAP_PACKAGE_NAME snap)
set(SNAP_PACK_TYPE "source")
set(SNAP_BASE "core22")

set(SNAPARCH_LIST_LINUX "${SNAP_ARCH_X86};${SNAP_ARCH_X86_64};${SNAP_ARCH_ARM};${SNAP_ARCH_ARM64}")
set(ALL_SNAPARCH_LIST_LINUX ${SNAPARCH_LIST_LINUX})
list(APPEND ALL_SNAPARCH_LIST_LINUX ${SNAP_ARCH_ALL})


message(STATUS "RELEASE_DATE: ${RELEASE_DATE}")

execute_process(
    COMMAND bash -c "date -d '${RELEASE_DATE}' '+%a, %d %b %Y 00:00:00 +0000'"
    OUTPUT_VARIABLE RELEASE_DATE_SNAP
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

message(STATUS "RELEASE_DATE_SNAP: ${RELEASE_DATE_SNAP}")

set(PACKAGE_ROOT_DIR "${CMAKE_BINARY_DIR}/${HOST_OS}/pkg/${SNAP_PACKAGE_NAME}/${APP_ARCH}/${APP_NAME}")
set(SNAP_ROOT_DIR "${CMAKE_BINARY_DIR}/snap")
set(SNAP_BUILD_ROOT_DIR "${SNAP_ROOT_DIR}")
set(SNAP_BUILD_CONFIG_DIR "${SNAP_ROOT_DIR}/${APP_NAME}/snap")
set(SNAP_BUILD_PAYLOAD_DIR "${SNAP_ROOT_DIR}/${APP_NAME}")
set(SNAP_BUILD_OUTPUT_DIR "${SNAP_ROOT_DIR}/output")
set(SNAP_BUILD_TEMP_DIR "${SNAP_ROOT_DIR}/temp")


