file(WRITE ${CONFIG_FILE_PATH} "$packageName = '${PROJECT_NAME}'\n")
file(APPEND ${CONFIG_FILE_PATH} "$packageNameWithBin = Join-Path -Path $packageName -ChildPath 'bin'\n")
file(APPEND ${CONFIG_FILE_PATH} "$installDir = Join-Path -Path $env:ProgramFiles -ChildPath $packageNameWithBin\n")
file(APPEND ${CONFIG_FILE_PATH} "\n")
file(APPEND ${CONFIG_FILE_PATH} "if (Test-Path $installDir) {\n")
file(APPEND ${CONFIG_FILE_PATH} "\tRemove-Item -Path $installDir -Recurse -Force\n")
file(APPEND ${CONFIG_FILE_PATH} "\tWrite-Output \"Removed installation directory: $installDir\"\n")
file(APPEND ${CONFIG_FILE_PATH} "} else {\n")
file(APPEND ${CONFIG_FILE_PATH} "\tWrite-Output \"Installation directory does not exist: $installDir\"\n")
file(APPEND ${CONFIG_FILE_PATH} "}\n")
file(APPEND ${CONFIG_FILE_PATH} "\n")

file(APPEND ${CONFIG_FILE_PATH} "\n")
file(APPEND ${CONFIG_FILE_PATH} "$existingPath = [System.Environment]::GetEnvironmentVariable('Path', [System.EnvironmentVariableTarget]::Machine)\n")
file(APPEND ${CONFIG_FILE_PATH} "$pathList = $existingPath -split ';'\n")
file(APPEND ${CONFIG_FILE_PATH} "if ($pathList -contains $installDir) {\n")
file(APPEND ${CONFIG_FILE_PATH} "\t$updatedPathList = $pathList | Where-Object { $_ -ne $installDir }\n")
file(APPEND ${CONFIG_FILE_PATH} "\t$newPath = ($updatedPathList -join ';')\n")
file(APPEND ${CONFIG_FILE_PATH} "\t[System.Environment]::SetEnvironmentVariable('Path', \"$newPath\", [System.EnvironmentVariableTarget]::Machine)\n")
file(APPEND ${CONFIG_FILE_PATH} "\tWrite-Output \"Removed $installDir from system PATH.\"\n")
file(APPEND ${CONFIG_FILE_PATH} "} else {\n")
file(APPEND ${CONFIG_FILE_PATH} "\tWrite-Output \"$installDir is not in the system PATH.\"\n")
file(APPEND ${CONFIG_FILE_PATH} "}\n")
file(APPEND ${CONFIG_FILE_PATH} "\n")

file(APPEND ${CONFIG_FILE_PATH} "$registryPath = \"HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\$packageName\"\n")
file(APPEND ${CONFIG_FILE_PATH} "\n")
file(APPEND ${CONFIG_FILE_PATH} "if (Test-Path $registryPath) {\n")
file(APPEND ${CONFIG_FILE_PATH} "\tRemove-Item -Path $registryPath -Recurse -Force\n")
file(APPEND ${CONFIG_FILE_PATH} "\tWrite-Output \"Removed Add/Remove Programs entry for $packageName.\"\n")
file(APPEND ${CONFIG_FILE_PATH} "} else {\n")
file(APPEND ${CONFIG_FILE_PATH} "\tWrite-Output \"No Add/Remove Programs entry found for $packageName.\"\n")
file(APPEND ${CONFIG_FILE_PATH} "}\n")
file(APPEND ${CONFIG_FILE_PATH} "\n")
file(APPEND ${CONFIG_FILE_PATH} "Write-Output 'Uninstallation completed successfully.'\n")
