

function(map_arch_to_debarch input_arch output_debarch)
    if(${input_arch} STREQUAL ${ARCH_X86})
        set(${output_debarch} ${DEB_ARCH_X86} PARENT_SCOPE)
    elseif(${input_arch} STREQUAL ${ARCH_X86_64})
        set(${output_debarch} ${DEB_ARCH_X86_64} PARENT_SCOPE)
    elseif(${input_arch} STREQUAL ${ARCH_ARM})
        set(${output_debarch} ${DEB_ARCH_ARM} PARENT_SCOPE)
    elseif(${input_arch} STREQUAL ${ARCH_ARM64})
        set(${output_debarch} ${DEB_ARCH_ARM64} PARENT_SCOPE)
    else()
        message(FATAL_ERROR "Unsupported architecture: ${input_arch}")
    endif()
endfunction()

function(map_debarch_to_arch input_debarch output_arch)
    if(${input_debarch} STREQUAL ${DEB_ARCH_X86})
        set(${output_arch} ${ARCH_X86} PARENT_SCOPE)
    elseif(${input_debarch} STREQUAL ${DEB_ARCH_X86_64})
        set(${output_arch} ${ARCH_X86_64} PARENT_SCOPE)
    elseif(${input_debarch} STREQUAL ${DEB_ARCH_ARM})
        set(${output_arch} ${ARCH_ARM} PARENT_SCOPE)
    elseif(${input_debarch} STREQUAL ${DEB_ARCH_ARM64})
        set(${output_arch} ${ARCH_ARM64} PARENT_SCOPE)
    else()
        message(FATAL_ERROR "Unsupported Debian architecture: ${input_debarch}")
    endif()
endfunction()



function(collect_vars result_var variable_list)
    set(vars "")
    set(added_vars "")

    foreach(var ${variable_list})
        if(NOT var IN_LIST added_vars)
            list(APPEND vars "-D${var}=${${var}} ")
            list(APPEND added_vars "${var}")
        endif()
    endforeach()
    set(${result_var} "${vars}" PARENT_SCOPE)
endfunction()


function(determine_deb_arch package_type deb_arch output_arch)
    if(NOT "${deb_arch}" STREQUAL "")
        map_arch_to_debarch("${deb_arch}" result_arch)
    else()
        if("${package_type}" STREQUAL "binary")
            map_arch_to_debarch("${APP_ARCH}" result_arch)
        else()
            set(result_arch "any")
        endif()
    endif()
    set(${output_arch} ${result_arch} PARENT_SCOPE)
endfunction()
# determine_deb_arch("${DEB_PACK_TYPE}" DEB_PACK_ARCH)
# message(WARNING "Debian Package Architecture: ${DEB_PACK_ARCH}")