include ./makefiles/variables.mk
include ./makefiles/init.mk



SOURCE_BUILD_ROOT_DIR = $(SOURCE_ROOT_DIR)/source
SOURCE_BUILD_CONFIG_DIR = $(SOURCE_BUILD_ROOT_DIR)
SOURCE_BUILD_PAYLOAD_DIR = $(SOURCE_BUILD_ROOT_DIR)
SOURCE_BUILD_TEMP_DIR = $(SOURCE_BUILD_ROOT_DIR)
SOURCE_BUILD_OUTPUT_DIR = $(SOURCE_BUILD_ROOT_DIR)/output

source-init:
	@mkdir -p $(DIST_ARTIFACTS_DIR)
	@mkdir -p $(SOURCE_BUILD_ROOT_DIR)
	@mkdir -p $(SOURCE_BUILD_CONFIG_DIR)
	@mkdir -p $(SOURCE_BUILD_PAYLOAD_DIR)
	@mkdir -p $(SOURCE_BUILD_TEMP_DIR)
	@mkdir -p $(SOURCE_BUILD_OUTPUT_DIR)


source.prepare.config : source-init

source.create-artifacts:
ifeq ($(APP_OS),$(OS_LINUX))
	tar -czvf $(DIST_ARTIFACTS_DIR)/$(APPLICATION_NAME)-$(APP_OS)-$(APP_TAG)-$(BUILD_ARCH)$(TAR_GZ_EXT) $(BIN_BUILD_OUTPUT_DIR)
	tar -cjvf $(DIST_ARTIFACTS_DIR)/$(APPLICATION_NAME)-$(APP_OS)-$(APP_TAG)-$(BUILD_ARCH)$(TAR_BZ2_EXT) $(BIN_BUILD_OUTPUT_DIR)
	zip $(DIST_ARTIFACTS_DIR)/$(APPLICATION_NAME)-$(APP_OS)-$(APP_TAG)-$(BUILD_ARCH)$(ZIP_EXT) $(BIN_BUILD_OUTPUT_DIR)
else ifeq ($(APP_OS),$(OS_WINDOWS))
	zip $(DIST_ARTIFACTS_DIR)/$(APPLICATION_NAME)-$(APP_OS)-$(APP_TAG)-$(BUILD_ARCH)$(ZIP_EXT) $(BIN_BUILD_OUTPUT_DIR)
	7z a $(DIST_ARTIFACTS_DIR)/$(APPLICATION_NAME)-$(APP_OS)-$(APP_TAG)-$(BUILD_ARCH)$(SEVEN_Z_EXT) $(BIN_BUILD_OUTPUT_DIR)
	rar a $(DIST_ARTIFACTS_DIR)/$(APPLICATION_NAME)-$(APP_OS)-$(APP_TAG)-$(BUILD_ARCH)$(RAR_EXT) $(BIN_BUILD_OUTPUT_DIR)
else ifeq ($(APP_OS),$(OS_MACOS))
	tar -czvf $(DIST_ARTIFACTS_DIR)/$(APPLICATION_NAME)-$(APP_OS)-$(APP_TAG)-$(BUILD_ARCH)$(TAR_GZ_EXT) $(BIN_BUILD_OUTPUT_DIR)
	tar -cjvf $(DIST_ARTIFACTS_DIR)/$(APPLICATION_NAME)-$(APP_OS)-$(APP_TAG)-$(BUILD_ARCH)$(TAR_BZ2_EXT) $(BIN_BUILD_OUTPUT_DIR)
	zip $(DIST_ARTIFACTS_DIR)/$(APPLICATION_NAME)-$(APP_OS)-$(APP_TAG)-$(BUILD_ARCH)$(ZIP_EXT) $(BIN_BUILD_OUTPUT_DIR)
else ifeq ($(APP_OS),$(OS_FREEBSD))
	tar -czvf $(DIST_ARTIFACTS_DIR)/$(APPLICATION_NAME)-$(APP_OS)-$(APP_TAG)-$(BUILD_ARCH)$(TAR_GZ_EXT) $(BIN_BUILD_OUTPUT_DIR)
	tar -cJvf $(DIST_ARTIFACTS_DIR)/$(APPLICATION_NAME)-$(APP_OS)-$(APP_TAG)-$(BUILD_ARCH)$(TAR_XZ_EXT) $(BIN_BUILD_OUTPUT_DIR)
	zip $(DIST_ARTIFACTS_DIR)/$(APPLICATION_NAME)-$(APP_OS)-$(APP_TAG)-$(BUILD_ARCH)$(ZIP_EXT) $(BIN_BUILD_OUTPUT_DIR)
else ifeq ($(APP_OS),$(OS_NETBSD))
	tar -czvf $(DIST_ARTIFACTS_DIR)/$(APPLICATION_NAME)-$(APP_OS)-$(APP_TAG)-$(BUILD_ARCH)$(TAR_GZ_EXT) $(BIN_BUILD_OUTPUT_DIR)
	tar -cJvf $(DIST_ARTIFACTS_DIR)/$(APPLICATION_NAME)-$(APP_OS)-$(APP_TAG)-$(BUILD_ARCH)$(TAR_XZ_EXT) $(BIN_BUILD_OUTPUT_DIR)
	zip $(DIST_ARTIFACTS_DIR)/$(APPLICATION_NAME)-$(APP_OS)-$(APP_TAG)-$(BUILD_ARCH)$(ZIP_EXT) $(BIN_BUILD_OUTPUT_DIR)
else ifeq ($(APP_OS),$(OS_OPENBSD))
	tar -czvf $(DIST_ARTIFACTS_DIR)/$(APPLICATION_NAME)-$(APP_OS)-$(APP_TAG)-$(BUILD_ARCH)$(TAR_GZ_EXT) $(BIN_BUILD_OUTPUT_DIR)
	tar -cJvf $(DIST_ARTIFACTS_DIR)/$(APPLICATION_NAME)-$(APP_OS)-$(APP_TAG)-$(BUILD_ARCH)$(TAR_XZ_EXT) $(BIN_BUILD_OUTPUT_DIR)
	zip $(DIST_ARTIFACTS_DIR)/$(APPLICATION_NAME)-$(APP_OS)-$(APP_TAG)-$(BUILD_ARCH)$(ZIP_EXT) $(BIN_BUILD_OUTPUT_DIR)
endif


