get_host_os(HOST_OS)
set(BREW_ARCH_X86_64 "x86_64")
set(BREW_ARCH_ARM64 "arm64")
set(BREW_ARCH_ALL "all")


set(BREW_PACKAGE_NAME brew)

set(BREWARCH_LIST_LINUX "${BREW_ARCH_X86_64};${BREW_ARCH_ARM64}")
set(ALL_BREWARCH_LIST_LINUX ${BREWARCH_LIST_LINUX})
list(APPEND ALL_BREWARCH_LIST_LINUX ${BREW_ARCH_ALL})


message(STATUS "RELEASE_DATE: ${RELEASE_DATE}")

execute_process(
    COMMAND bash -c "date -d '${RELEASE_DATE}' '+%a, %d %b %Y 00:00:00 +0000'"
    OUTPUT_VARIABLE RELEASE_DATE_BREW
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

message(STATUS "RELEASE_DATE_BREW: ${RELEASE_DATE_BREW}")

set(PACKAGE_ROOT_DIR "${CMAKE_BINARY_DIR}/${HOST_OS}/pkg/${BREW_PACKAGE_NAME}/${APP_ARCH}/${APP_NAME}")
set(BREW_ROOT_DIR "${CMAKE_BINARY_DIR}/brew")
set(BREW_BUILD_ROOT_DIR "${BREW_ROOT_DIR}")
set(BREW_BUILD_CONFIG_DIR "${BREW_ROOT_DIR}/${APP_NAME}/brew")
set(BREW_BUILD_PAYLOAD_DIR "${BREW_ROOT_DIR}/${APP_NAME}")
set(BREW_BUILD_OUTPUT_DIR "${BREW_ROOT_DIR}/output")
set(BREW_BUILD_TEMP_DIR "${BREW_ROOT_DIR}/temp")


