file(APPEND ${CONFIG_FILE_PATH} "name: ${APP_NAME}\n")
file(APPEND ${CONFIG_FILE_PATH} "version: '${RAW_VERSION}'\n")
file(APPEND ${CONFIG_FILE_PATH} "summary: ${SUMMARY}\n")
file(APPEND ${CONFIG_FILE_PATH} "description: ${PROJECT_DESCRIPTION}\n\n")
file(APPEND ${CONFIG_FILE_PATH} "base: ${SNAP_BASE}\n")
file(APPEND ${CONFIG_FILE_PATH} "grade: stable\n")
file(APPEND ${CONFIG_FILE_PATH} "confinement: strict\n\n")

file(APPEND ${CONFIG_FILE_PATH} "apps:\n")
file(APPEND ${CONFIG_FILE_PATH} "  ${APP_NAME}:\n")
file(APPEND ${CONFIG_FILE_PATH} "    command: bin/${APP_NAME}\n\n")

file(APPEND ${CONFIG_FILE_PATH} "parts:\n")
file(APPEND ${CONFIG_FILE_PATH} "  ${APP_NAME}:\n")
file(APPEND ${CONFIG_FILE_PATH} "    source: .\n")
file(APPEND ${CONFIG_FILE_PATH} "    plugin: go\n")
file(APPEND ${CONFIG_FILE_PATH} "    build-snaps: [go/latest/stable]\n")
file(APPEND ${CONFIG_FILE_PATH} "    source-type: local\n")
file(APPEND ${CONFIG_FILE_PATH} "    build-packages: [git,cmake,make]\n")

file(APPEND ${CONFIG_FILE_PATH} "    override-build: |\n")
file(APPEND ${CONFIG_FILE_PATH} "      mkdir -p \$SNAPCRAFT_PART_INSTALL/bin\n")
file(APPEND ${CONFIG_FILE_PATH} "      make build.cmake.linux VERSION=${APP_TAG}\n")
file(APPEND ${CONFIG_FILE_PATH} "      make build.binary OUTPUT=\$SNAPCRAFT_PART_INSTALL/bin\n")
