get_host_os(HOST_OS)
set_os_ext(${HOST_OS} EXT)
set(CMAKE_SOURCE_DIR_PATH ${CMAKE_SOURCE_DIR})
set(COMMON_VARIABLES 
    PROJECT_NAME
    APP_NAME
    APP_TAG
    VERSION_SEMVER
    RAW_VERSION
    CHANGELOG_PATH
    PROJECT_GIT
    PROJECT_MAINTANER
    PROJECT_ORGANIZATION
    PROJECT_LICENCE_URL
    RELEASE_DATE_CHOCO
    PROJECT_ICON_URL
    PROJECT_HOMEPAGE
    PROJECT_SUMMARY
    PROJECT_DESCRIPTION
    PROJECT_TAGS
    LINUX_APP_BINARY_DIR
    LINUX_APP_DATA_DATABASE_DIR
    CMAKE_SOURCE_DIR_PATH
    DIST_ROOT_DIR
    GOOS
    EXT
    ARCH_X86
    ARCH_X86_64
    ARCH_ARM64
    ARCH_ALL
    CHOCO_ARCH_X86
    CHOCO_ARCH_X86_64
    CHOCO_ARCH_ARM64
    CHOCO_ARCH_ALL
)




file(GLOB_RECURSE CHOCO_FILES "${CMAKE_CURRENT_LIST_DIR}/choco-files/*")

foreach(CHOCOARCH ${ALL_CHOCOARCH_LIST_WINDOWS})
    map_chocoarch_to_arch_all(${CHOCOARCH} APP_ARCH)
    
    set(CHOCO_ROOT_DIR ${CMAKE_SOURCE_DIR}/${DIST_ROOT_DIR}/${APP_TAG}/${HOST_OS}/pkg/${CHOCO_PACKAGE_NAME}/${APP_ARCH})
    set(CHOCO_PAYLOAD_DIR ${CHOCO_ROOT_DIR}/${APP_NAME})
    set(CHOCO_OUTPUT_DIR ${CHOCO_ROOT_DIR}/output)
    set(CHOCO_CONF_DIR ${CHOCO_ROOT_DIR}/${APP_NAME})

    if(${CHOCOARCH} STREQUAL ${CHOCO_ARCH_ALL})
        get_host_arch(HOST_ARCH)
        set(BIN_OUTPUT_FULL_PATH ${CHOCO_OUTPUT_DIR}/${APP_NAME}/${DIST_ROOT_DIR}/${APP_TAG}/${HOST_OS}/bin/${HOST_ARCH}/${APP_NAME}${EXT})
    else()
        set(BIN_OUTPUT_FULL_PATH ${CHOCO_OUTPUT_DIR}/${APP_NAME}/${DIST_ROOT_DIR}/${APP_TAG}/${HOST_OS}/bin/${APP_ARCH}/${APP_NAME}${EXT})
    endif()


    list(APPEND COMMON_VARIABLES APP_ARCH)
    list(APPEND COMMON_VARIABLES CHOCOARCH)
    list(APPEND COMMON_VARIABLES BIN_OUTPUT_FULL_PATH)

    set(CHOCO_FILE_NAMES "")
    foreach(CHOCOFILE ${CHOCO_FILES})
        file(RELATIVE_PATH REL_FILE_PATH "${CMAKE_CURRENT_LIST_DIR}/choco-files" ${CHOCOFILE})

        set(CONFIG_FILE_PATH "${CHOCO_CONF_DIR}/${REL_FILE_PATH}")
        list(APPEND CHOCO_FILE_NAMES ${CONFIG_FILE_PATH})
        list(APPEND COMMON_VARIABLES CONFIG_FILE_PATH)

        var_list_to_cmake_args(VARIABLES_TO_PASS "${COMMON_VARIABLES}")
        add_custom_command(
            OUTPUT ${CONFIG_FILE_PATH}
            COMMAND ${CMAKE_COMMAND} -E echo "Generating ${CHOCOFILE} file..."
            COMMAND ${CMAKE_COMMAND} ${VARIABLES_TO_PASS}  -P "${CHOCOFILE}"
            COMMENT "Generating ${CHOCOFILE} to ${CONFIG_FILE_PATH}"
        )
    endforeach()


    add_custom_target(build.choco.package.${APP_ARCH}.configuration DEPENDS check_env_for_choco_packing ${CHOCO_FILE_NAMES})
endforeach()