name: Manual Release Branch Management

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout dev branch
      uses: actions/checkout@v3
      with:
        ref: dev

    - name: Get WORKING_VERSION from VERSION file
      uses: ./.github/actions/get-version

    - name: Shift dev to release
      uses: ./.github/actions/shift-dev-to-release
