name: Dev Workflow

on:
  push:
    branches:
      - dev

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Set and Retrieve Github ENV variables
              run: |
                # define variables      
                tests=16
                failures=2

                # set them as GitHub ENV variables
                echo "Tests=$tests" >> $GITHUB_ENV
                echo "Failures=$failures" >> $GITHUB_ENV

                # retrieve these GitHub ENV variables
                echo "${{ env.Failures }} out of ${{ env.Tests }} tests failed on CI"

    #   - name: Bump DEV version
    #     run: |
    #       if [[ -z "${{ env.WORKING_VERSION }}" ]]; then
    #         echo "WORKING_VERSION=v1.0.0-dev.1" >> $GITHUB_ENV
    #       else
    #         echo "Updating WORKING_VERSION to ${WORKING_VERSION}" >> $GITHUB_ENV
    #       fi


    #   - name: Print WORKING_VERSION
    #     run: echo "WORKING_VERSION is $WORKING_VERSION"