name: Dev Workflow

on:
  push:
    branches:
      - dev


jobs:
  env:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3


      - name: Ensure VERSION exists
        run: |
          if [ ! -f VERSION ]; then
            echo "v1.0.0-dev.1" > VERSION
          fi

      - name: Bump DEV version
        run: |
          version=$(cat VERSION)
          if [[ -z "$version" ]]; then
            version="v1.0.0-dev.1"
            echo $version > VERSION
          else
            version=$(echo $version | awk -F. -v OFS=. '{$3+=1; print}')
            echo $version > VERSION
          fi
          echo "WORKING_VERSION=$version" >> $GITHUB_ENV

      - name: Commit and push updated version
        run: | 
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add VERSION
          git commit -m "Bump dev version to $WORKING_VERSION"
          git push origin dev