name: Dev Workflow

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Bump DEV version
        run: |
          if [[ -z "${{ env.WORKING_VERSION }}" ]]; then
            echo "WORKING_VERSION=v1.0.0-dev.1" >> $GITHUB_ENV
          else
            echo "Updating WORKING_VERSION to ${WORKING_VERSION}" >> $GITHUB_ENV
          fi
