name: Dev Workflow

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.x'

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Bump DEV version
        run: |
          if [[ -z "${{ env.WORKING_VERSION }}" ]]; then
            echo "WORKING_VERSION=v1.0.0-dev.1" >> $GITHUB_ENV
          else
            echo "Updating WORKING_VERSION to ${WORKING_VERSION}" >> $GITHUB_ENV
          fi
