name: Dev Workflow

on:
  push:
    branches:
      - dev

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set env
              run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
            - name: Test
              run: echo $GITHUB_SHA_SHORT

    #   - name: Bump DEV version
    #     run: |
    #       if [[ -z "${{ env.WORKING_VERSION }}" ]]; then
    #         echo "WORKING_VERSION=v1.0.0-dev.1" >> $GITHUB_ENV
    #       else
    #         echo "Updating WORKING_VERSION to ${WORKING_VERSION}" >> $GITHUB_ENV
    #       fi


    #   - name: Print WORKING_VERSION
    #     run: echo "WORKING_VERSION is $WORKING_VERSION"