name: Pars CLI

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
    - '!*-rc[0-9]+'

jobs:
  build-linux-386:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build Binary
        working-directory: ./src
        run: |
          mkdir -p ../releases
          GOOS=linux GOARCH=386 go build -o ../releases/bin ./pars.go

      - name: Archive Binary Build
        run: | 
          tar -czvf releases/pars-linux-386.bin.tar.gz -C releases/ bin
          ls releases

      - name: Upload Linux 386 Artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-386-build
          path: |
            releases/pars-linux-386.bin.tar.gz





  package-linux-389-deb:
    needs: 
      - build-linux-386
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Tag Name
        id: get_tag_name
        run: |
          echo "Tag name is: ${{ github.ref }}"
          TAG_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
          echo "tag_name=$TAG_NAME" >> $GITHUB_ENV



      - name: Download Linux 386 Artifact
        uses: actions/download-artifact@v2
        with:
          name: linux-386-build
          path: downloads


      - name: Build .deb Package
        run: |
          ls downloads

          mkdir -p releases/deb/DEBIAN
          mkdir -p releases/deb/usr/local/bin
          cp ./downloads releases/deb/usr/local/bin/
          echo "Package: Pars" > releases/deb/DEBIAN/control
          echo "Version: ${{ env.version }}" >> releases/deb/DEBIAN/control
          echo "Section: base" >> releases/deb/DEBIAN/control
          echo "Priority: optional" >> releases/deb/DEBIAN/control
          echo "Architecture: i386" >> releases/deb/DEBIAN/control
          echo "Depends: libc6 (>= 2.7)" >> releases/deb/DEBIAN/control
          echo "Maintainer: Pars Dev Kit <info@parsdevkit.net>" >> releases/deb/DEBIAN/control
          echo "Description: Pars" >> releases/deb/DEBIAN/control
          
          dpkg-deb --build releases/deb releases/pars-linux-386.deb


      - name: Archive .deb Package
        run: tar -czvf releases/pars-linux-386.deb.tar.gz -C releases/ pars-linux-386.deb



      - name: Upload Linux 386 Artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-386-build
          path: |
            releases/pars-linux-386.deb.tar.gz


  create_release:
    needs: 
      - package-linux-389-deb
    runs-on: ubuntu-latest

    steps:

      - name: Get Tag Name
        id: get_tag_name
        run: |
          echo "Tag name is: ${{ github.ref }}"
          TAG_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
          echo "tag_name=$TAG_NAME" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.tag_name }}
          release_name: Release ${{ env.tag_name }}
          body: "test"
          draft: false
          prerelease: false






      #  386


      - name: Download Linux 386 Artifact
        uses: actions/download-artifact@v2
        with:
          name: linux-386-build
          path: releases





      - name: Upload Linux 386 Binary Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./releases/pars-linux-386.bin.tar.gz
          asset_name: pars-linux-386.tar.gz
          asset_content_type: application/gzip

          
      - name: Upload Linux 386 .deb Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./releases/pars-linux-386.deb.tar.gz
          asset_name: pars-linux-386.deb.tar.gz
          asset_content_type: application/gzip



